### PR TITLE
Enable testing on Python 3.12

### PR DESCRIPTION
**Pull request by martymichal**
Python 3.12 was released a few days ago[0], so enabling testing on it is welcome.

[0] https://docs.python.org/dev/whatsnew/3.12.html

### CODE REVIEW

**Comment by JiriPavela** [comment]
Ok, so although Perun codebase itself is now ready for 3.12, it seems like some of our dependencies not so much. The `capstone` python binding (used by `angr`) is still using distutils (https://github.com/capstone-engine/capstone/issues/2005). While we could make `angr` an on-demand import to bypass this import issue on startup, it is currently our only tool for extracting CG and CFG of profiled binaries. For this reason, I suggest we wait until all our important dependencies are ready for 3.12.

**Comment by tfiedor** [comment]
> Ok, so although Perun codebase itself is now ready for 3.12, it seems like some of our dependencies not so much. The `capstone` python binding (used by `angr`) is still using distutils ([capstone-engine/capstone#2005](https://github.com/capstone-engine/capstone/issues/2005)). While we could make `angr` an on-demand import to bypass this import issue on startup, it is currently our only tool for extracting CG and CFG of profiled binaries. For this reason, I suggest we wait until all our important dependencies are ready for 3.12.

Indeed, I champion this suggestion. I don't think this is critical requirement (while it would be nice, we can wait few months, whether capstone developers will move forward with Python 3.12 support; if not we might fix it for them or circumvent the dependencies in some other way).

**Review by tfiedor — APPROVED** [review]

**Comment by tfiedor** [comment]
I'm opening this issue and checking out if we can support py3.12 (it is really needed now).

**Comment by tfiedor** [comment]
Good, I'm merging this, thank you Jirka and Ondra for making this work :-). We will need to apply Perun on Python 3.12. soon.

**Pull request merged**
